task:
  name: gcc8-Release-FullBuild
  container:
    image: conanio/gcc8
  build_script:
  - sudo apt-get update
  - sudo apt-get install --assume-yes git
  - sudo apt-cache policy cmake
  - pwd
  - gcc-8 --version
  - cmake --version
  - conan --version
  - mkdir build
  - cd build
  - conan install ..
  - cmake ..
  - VERBOSE=1 cmake --build . --config "Release"
  test_script:
  - pwd
  - cd build
  - ctest -j2 -C Release
