image:
  - Visual Studio 2017
clone_folder: c:\projects\source
install:
- cmd: >-
    set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Scripts

    pip install --user conan

    cmake --version

    conan --version

build_script:
- cmd: >-
    mkdir build

    cd build

    conan install c:\projects\source

    cmake c:\projects\source -G "Visual Studio 15"
    
    cmake --build . --config "Release"

test_script:
- cmd: ctest -C Release
