image:
  - Visual Studio 2017
install:
  - cinst cmake --version 3.13.4
  - ps: set PATH=%PATH%;C:\Users\appveyor\AppData\Roaming\Python\Scripts
  - ps: pip install --user conan
clone_folder: c:\projects\source
build_script:
- cmd: >-
    cmake --version

    conan --version

    mkdir build

    cd build
    
    conan install c:\projects\source
    
    cmake c:\projects\source -G "Visual Studio 15"
    
    cmake --build . --config "Release"

test_script:
- cmd: ctest -C Release
